# com.horstmann.codecheck.storage.local=/opt/codecheck/repo
com.horstmann.codecheck.storage.type=sql
db.default.url="jdbc:postgresql://ep-late-wildflower-ax5fz8es-pooler.c-4.us-east-2.aws.neon.tech/neondb?user=neondb_owner&password=npg_xL9aZpQIqjg8&sslmode=require&channelBinding=require"
com.horstmann.codecheck.comrun.local=/opt/codecheck/comrun
com.horstmann.codecheck.jwt.secret.key=changeme
com.horstmann.codecheck.home=assets/uploadProblem.html

quarkus.http.port=8080
quarkus.index-dependency.resteasy-multipart.group-id=org.jboss.resteasy
quarkus.index-dependency.resteasy-multipart.artifact-id=resteasy-multipart-provider
quarkus.http.access-log.enabled=true
quarkus.http.limits.max-form-attribute-size=16K